name: Update Cert

on:
  schedule:
    - cron: '0 10 1 * *'
  # add a tag to trigger manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          curl https://get.acme.sh | sh -s email=my@example.com
          pip install -r requirements.txt

      - name: Update Cert
        env:
          # 环境变量根据实际情况自行修改或增删，未设置则使用默认值（参见update.sh）
          DP_Id: ${{ secrets.DP_Id }}
          DP_Key: ${{ secrets.DP_Key }}
          CF_Token: ${{ secrets.CF_TOKEN }}
          CF_Account_ID: ${{ secrets.CF_ACCOUNT_ID }}
          ACME_DNS_TYPE: ${{ secrets.ACME_DNS_TYPE }}
          ACME_DOMAIN: ${{ secrets.ACME_DOMAIN }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
          CDN_DOMAIN: ${{ secrets.CDN_DOMAIN }}
          UPDATE_SSL: ${{ secrets.UPDATE_SSL }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          DELETE_OLD_CERTS: ${{ secrets.DELETE_OLD_CERTS }}
          PUSH_URL: ${{ secrets.PUSH_URL }}
          PURGE_URL: ${{ secrets.PURGE_URL }}
          ENABLE_HSTS: ${{ secrets.ENABLE_HSTS }}
          ENABLE_OCSP: ${{ secrets.ENABLE_OCSP }}
          ENABLE_HTTP2: ${{ secrets.ENABLE_HTTP2 }}
          CERT_HOME: /home/runner/.acme.sh
          ACME_HOME: /home/runner/.acme.sh
          WORK_DIR: .
        run: sh ./docker/update.sh

      - name: Notification
        if: always()
        run: |
          curl -X POST \
            -H "Content-Type: application/json;charset=utf-8" \
            "https://sctapi.ftqq.com/${{ secrets.SERVERCHAN_KEY }}.send" \
            -d '{"title":"Github Actions", "desp":"Your tencent cdn certs update ${{ job.status }}"}'
