name: Update Cert

on:
  schedule:
    - cron: '0 10 1 * *'
  # add a tag to trigger manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          curl https://get.acme.sh | sh -s email=my@example.com
          pip install -r requirements.txt

      - name: Update Cert
        env:
          DP_Id: ${{ secrets.DP_Id }}
          DP_Key: ${{ secrets.DP_Key }}
          ACME_DNS_TYPE: ${{ secrets.ACME_DNS_TYPE }}
          ACME_DOMAIN: ${{ secrets.ACME_DOMAIN }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
          CDN_DOMAIN: ${{ secrets.CDN_DOMAIN }}
          CERT_HOME: /home/runner/.acme.sh
          ACME_HOME: /home/runner/.acme.sh
          WORK_DIR: .
        run: sh ./docker/update.sh

      - name: Notification
        if: always()
        run: |
          curl -X POST \
            -H "Content-Type: application/json;charset=utf-8" \
            "https://sctapi.ftqq.com/${{ secrets.SERVERCHAN_KEY }}.send" \
            -d '{"title":"Github Actions", "desp":"Your tencent cdn certs update ${{ job.status }}"}'
